[project]
name = "scrapper-tas"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.12.3",
    "fake-useragent>=1.5.1",
    "pandas>=2.2.3",
    "requests>=2.32.3",
    "selenium>=4.25.0",
]
